/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kelompok12.layout.user;

import javax.swing.JOptionPane;

import kelompok12.database.model.UserModel;
import kelompok12.database.repo.UserRepository;
import kelompok12.projectbp1.Utama;

/**
 *
 * @author Fujitsu U938
 */
public class MenuUser extends javax.swing.JFrame {

    private static UserModel loginSuccess;

    /**
     * Creates new form MenuUser
     *
     * @param loginSuccess
     */
    public MenuUser(UserModel loginSuccess) {
        MenuUser.loginSuccess = loginSuccess;
        initComponents();
        Home();
    }

    public void Home() {
        User user = new User(loginSuccess);
        Konten.removeAll();
        Konten.add(user.getContentPane(), java.awt.BorderLayout.CENTER);
        Konten.revalidate();
        Konten.repaint();
    }

    public void DeleteFungsi() {
        String id = loginSuccess.getId();
        UserRepository repo = new UserRepository();
        repo.delete(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Konten = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        HomeMenu = new javax.swing.JMenu();
        TransaksiMenu = new javax.swing.JMenu();
        TarikMenu = new javax.swing.JMenuItem();
        TransferMenu = new javax.swing.JMenuItem();
        RiwayatTransaksiMenu = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        EditUserMenu = new javax.swing.JMenuItem();
        HapusUserMenu = new javax.swing.JMenuItem();
        LogoutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Konten.setBackground(new java.awt.Color(227, 242, 253));
        Konten.setPreferredSize(new java.awt.Dimension(500, 800));

        javax.swing.GroupLayout KontenLayout = new javax.swing.GroupLayout(Konten);
        Konten.setLayout(KontenLayout);
        KontenLayout.setHorizontalGroup(
            KontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        KontenLayout.setVerticalGroup(
            KontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(227, 242, 253));

        HomeMenu.setText("Home");
        HomeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMenuMouseClicked(evt);
            }
        });
        HomeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(HomeMenu);

        TransaksiMenu.setText("Transaksi");

        TarikMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        TarikMenu.setBackground(new java.awt.Color(227, 242, 253));
        TarikMenu.setText("Tarik");
        TarikMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarikMenuActionPerformed(evt);
            }
        });
        TransaksiMenu.add(TarikMenu);

        TransferMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        TransferMenu.setBackground(new java.awt.Color(227, 242, 253));
        TransferMenu.setText("Transfer");
        TransferMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferMenuActionPerformed(evt);
            }
        });
        TransaksiMenu.add(TransferMenu);

        RiwayatTransaksiMenu.setBackground(new java.awt.Color(227, 242, 253));
        RiwayatTransaksiMenu.setText("Riwayat Transaksi");
        RiwayatTransaksiMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiwayatTransaksiMenuActionPerformed(evt);
            }
        });
        TransaksiMenu.add(RiwayatTransaksiMenu);

        jMenuBar1.add(TransaksiMenu);

        EditMenu.setText("Edit User");

        EditUserMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        EditUserMenu.setBackground(new java.awt.Color(227, 242, 253));
        EditUserMenu.setText("Edit User");
        EditUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUserMenuActionPerformed(evt);
            }
        });
        EditMenu.add(EditUserMenu);

        HapusUserMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        HapusUserMenu.setBackground(new java.awt.Color(255, 0, 102));
        HapusUserMenu.setText("Hapus User");
        HapusUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusUserMenuActionPerformed(evt);
            }
        });
        EditMenu.add(HapusUserMenu);

        jMenuBar1.add(EditMenu);

        LogoutMenu.setText("Logout");
        LogoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(LogoutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Konten, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Konten, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMenuMouseClicked
        // Terminate the current session
        loginSuccess = null;
        // Navigate to the Utama screen
        setVisible(false);
        Utama utama = new Utama();
        utama.setVisible(true);
    }//GEN-LAST:event_LogoutMenuMouseClicked

    private void RiwayatTransaksiMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiwayatTransaksiMenuActionPerformed
        RiwayatTransaksiUser rt = new RiwayatTransaksiUser(loginSuccess);
        Konten.removeAll();
        Konten.add(rt.getContentPane(), java.awt.BorderLayout.CENTER);
        Konten.revalidate();
        Konten.repaint();
    }//GEN-LAST:event_RiwayatTransaksiMenuActionPerformed

    private void TarikMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TarikMenuActionPerformed
        Tarik tarik = new Tarik(loginSuccess);
        Konten.removeAll();
        Konten.add(tarik.getContentPane(), java.awt.BorderLayout.CENTER);
        Konten.revalidate();
        Konten.repaint();
    }// GEN-LAST:event_TarikMenuActionPerformed

    private void EditUserMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EditUserMenuActionPerformed
        Edit edit = new Edit(loginSuccess);
        Konten.removeAll();
        Konten.add(edit.getContentPane(), java.awt.BorderLayout.CENTER);
        Konten.revalidate();
        Konten.repaint();
    }// GEN-LAST:event_EditUserMenuActionPerformed

    private void HomeMenuMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_HomeMenuMouseClicked
        Home();
    }// GEN-LAST:event_HomeMenuMouseClicked

    private void HapusUserMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HapusUserMenuActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this user?",
                "Confirm", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            DeleteFungsi();

            JOptionPane.showMessageDialog(this, "User has been deleted");

            Utama utama = new Utama();
            setVisible(false);
            utama.setVisible(true);
        }
    }// GEN-LAST:event_HapusUserMenuActionPerformed

    private void TransferMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TransferMenuActionPerformed
        Transfer transfer = new Transfer(loginSuccess);
        Konten.removeAll();
        Konten.add(transfer.getContentPane(), java.awt.BorderLayout.CENTER);
        Konten.revalidate();
        Konten.repaint();
    }// GEN-LAST:event_TransferMenuActionPerformed

    private void HomeMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HomeMenuActionPerformed
        Home();
    }// GEN-LAST:event_HomeMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUser(loginSuccess).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenuItem EditUserMenu;
    private javax.swing.JMenuItem HapusUserMenu;
    private javax.swing.JMenu HomeMenu;
    private javax.swing.JPanel Konten;
    private javax.swing.JMenu LogoutMenu;
    private javax.swing.JMenuItem RiwayatTransaksiMenu;
    private javax.swing.JMenuItem TarikMenu;
    private javax.swing.JMenu TransaksiMenu;
    private javax.swing.JMenuItem TransferMenu;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
