name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_jdk_21:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Verify Maven version
        run: mvn -version

      - name: Clean and Install dependencies
        run: mvn clean install -DskipTests --file ProjectBP1/pom.xml

      - name: Build the project with JDK 21
        run: mvn -B package -DskipTests --file ProjectBP1/pom.xml

      - name: Rename artifact for JDK 21
        run: mv ProjectBP1/target/*.jar ProjectBP1/target/project-build-jdk21.jar

      - name: Upload artifact for JDK 21
        uses: actions/upload-artifact@v4.4.3
        with:
          name: java-build-artifact-jdk21
          path: ProjectBP1/target/project-build-jdk21.jar

  build_jdk_17:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Verify Maven version
        run: mvn -version

      - name: Clean and Install dependencies
        run: mvn clean install -DskipTests --file ProjectBP1/pom.xml

      - name: Build the project with JDK 17
        run: mvn -B package -DskipTests --file ProjectBP1/pom.xml

      - name: Rename artifact for JDK 17
        run: mv ProjectBP1/target/*.jar ProjectBP1/target/project-build-jdk17.jar

      - name: Upload artifact for JDK 17
        uses: actions/upload-artifact@v4.4.3
        with:
          name: java-build-artifact-jdk17
          path: ProjectBP1/target/project-build-jdk17.jar

  build_jdk_8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Verify Maven version
        run: mvn -version

      - name: Clean and Install dependencies
        run: mvn clean install -DskipTests --file ProjectBP1/pom.xml

      - name: Build the project with JDK 8
        run: mvn -B package -DskipTests --file ProjectBP1/pom.xml

      - name: Rename artifact for JDK 8
        run: mv ProjectBP1/target/*.jar ProjectBP1/target/project-build-jdk8.jar

      - name: Upload artifact for JDK 8
        uses: actions/upload-artifact@v4.4.3
        with:
          name: java-build-artifact-jdk8
          path: ProjectBP1/target/project-build-jdk8.jar
